name: Test SSH Clone  
on:  
  push:  
    branches: [main]  
  workflow_dispatch:  # Allows manual triggering [[10]]  

jobs:  
  test-clone:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Install SSH key  
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa  
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Server’s private key [[10]]  
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts  # Trust the server [[10]]  

      - name: Connect and clone repo  
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.SERVER_IP }} "  
            if [ ! -d '/var/www/OpenBlogAI' ]; then  
              git clone git@github.com:xloyb/OpenBlogAI.git /var/www/OpenBlogAI  
            else  
              echo 'Repo already exists'  
            fi  
          "  
        env:  
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
          USER: ${{ secrets.USER }}  
          SERVER_IP: ${{ secrets.SERVER_IP }}  