name: Node.js CI/CD with Prisma  
on:  
  push:  
    branches: [main]  

jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  
    steps:  
      # Checkout code  
      - uses: actions/checkout@v4  
        with:  
          repository: xloyb/OpenBlogAI  
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Key for GitHub repo access [[7]]  

      # Set up Node.js  
      - uses: actions/setup-node@v4  
        with:  
          node-version: 20  

      # Install dependencies in the "server" directory  
      - name: Install dependencies  
        run: npm ci  
        working-directory: server  

      # Deploy to Ubuntu server  
      - name: Deploy to Server  
        uses: appleboy/ssh-action@v1.0.0  
        with:  
          host: ${{ secrets.SERVER_IP }}  
          username: ${{ secrets.USER }}  
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}  # Separate key for server access [[7]][[9]]  
          use_insecure_cipher: true  # For older cipher compatibility [[7]]  
          script: |  
            set -e  # Fail on errors [[7]]  

            # Ensure SSH agent is running and add deploy key for GitHub  
            eval "$(ssh-agent -s)"  
            echo "${{ secrets.GITHUB_DEPLOY_KEY }}" > ~/.ssh/github_deploy_key  
            chmod 600 ~/.ssh/github_deploy_key  
            ssh-add ~/.ssh/github_deploy_key  # [[7]]  

            # Install Node.js and PM2 if missing  
            if ! command -v node &> /dev/null; then  
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -  
              sudo apt-get install -y nodejs  
            fi  
            if ! command -v pm2 &> /dev/null; then  
              npm install pm2 -g  
            fi  

            # Clone repo if not exists (uses GitHub deploy key)  
            if [ ! -d "/var/www/OpenBlogAI" ]; then  
              GIT_SSH_COMMAND="ssh -i ~/.ssh/github_deploy_key" git clone git@github.com:xloyb/OpenBlogAI.git /var/www/OpenBlogAI  
            fi  

            # Navigate to server directory and update code  
            cd /var/www/OpenBlogAI/server  
            GIT_SSH_COMMAND="ssh -i ~/.ssh/github_deploy_key" git pull origin main  

            # Install dependencies and regenerate Prisma Client  
            npm install --production  
            npx prisma generate --schema=./prisma/schema.prisma --no-engine  # [[7]][[9]]  

            # Run database migrations  
            npx prisma migrate deploy  

            # Test database connection  
            echo "Testing database connection..."  
            node -e "  
              const { PrismaClient } = require('@prisma/client');  
              const prisma = new PrismaClient();  
              prisma.$connect()  
                .then(() => {  
                  console.log('✅ Database connection successful!');  
                  process.exit(0);  
                })  
                .catch((err) => {  
                  console.error('❌ Database connection failed:', err);  
                  process.exit(1);  
                });  
              setTimeout(() => {  
                console.error('❌ Connection timed out');  
                process.exit(1);  
              }, 10000);  
            " || exit 1  

            # Restart the app  
            pm2 restart app.js  