name: Node.js CI/CD SETUP
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20 

      # Install dependencies in the "server" directory
      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      # Run tests (if applicable)
      - name: Run tests
        run: npm test
        working-directory: ./server

      # Deploy to Ubuntu server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/OpenBlogAI/server
            git pull origin main
            npm install --production
            npx prisma generate
            pm2 restart app.js
