name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install server dependencies
      working-directory: server
      run: npm ci

    - name: Build server
      working-directory: server
      run: npm run build

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/openblogai/OpenBlogAI/server
          git fetch origin main
          git reset --hard origin/main
          npm ci
          npm run build
          pm2 restart ecosystem.config.js
