name: Deploy Server to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set up environment variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd server
          npm ci

      - name: Build server (if necessary)
        run: |
          cd server
          npm run build # Only if your app requires a build step

      - name: Run Prisma migrations
        run: |
          cd server
          echo "Running Prisma migrations..."
          npx prisma migrate deploy # Ensure DATABASE_URL is properly set

      - name: Debug SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts # Avoids SSH authenticity prompt
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH Connection successful'"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Successfully connected to the server"
            if [ ! -d "/var/www/openblogai" ]; then
              echo "Repository not found, cloning..."
              git clone https://github.com/xloyb/openblogai.git /var/www/openblogai 
            fi
            cd /var/www/openblogai
            git pull origin main
            cd /var/www/openblogai/server
            npm ci --production
            npx prisma generate
            pm2 reload /var/www/openblogai/ecosystem.config.js

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
