name: Deploy 

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Adjust version as needed
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build  # Modify if your build command is different
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/openblogai/server
          git pull
          npm ci
          npm run build
          pm2 restart ecosystem.config.js  # Adjust if your PM2 command is different