name: Deploy Server to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Build server
        run: |
          cd server
          npm run build

      - name: Run Prisma migrations
        run: |
          cd server
          npx prisma migrate deploy

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/openblogai
            git pull origin main
            cd server
            npm ci --production
            npx prisma generate
            pm2 reload ecosystem.config.js
